In [ ]:
#single dimensional array in numpy

In [1]:
import numpy as np
list1=[1,2,3,4,5]
np.array(list1)

array([1, 2, 3, 4, 5])

In [ ]:
#two dimensional array in numpy

In [2]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#zeroes numpy

In [5]:
np.zeros((1,2))

array([[0., 0.]])

In [6]:
np.full((2,2),7)  #full function in numpy

array([[7, 7],
       [7, 7]])

In [9]:
np.arange(1,30)   #Range function in numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#shapes in numpy-->shapes are used to change the matrix rows and columns

In [10]:
n2=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(n2)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [11]:
print(n2.shape)

(2, 6)


In [12]:
n2.shape=(6,2)

In [17]:
print(n2)

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [20]:
n2.shape=(2,6)
print(n2)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [25]:
import numpy as np
n1=np.array([1,2,3,4,5])
n2=np.array([6,7,8,9,10])
np.vstack((n1,n2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
np.hstack((n1,n2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.column_stack((n1,n2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])